# Generated by Django 6.0.3 on 2026-04-05 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('romaneios_count', models.IntegerField(default=0)),
                ('abastecimentos_count', models.IntegerField(default=0)),
                ('adiantamentos_count', models.IntegerField(default=0)),
                ('motoristas_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='OK', max_length=20)),
                ('erro', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('placa', models.CharField(db_index=True, max_length=20)),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('nome', 'placa')},
            },
        ),
        migrations.CreateModel(
            name='Adiantamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(choices=[('SF', 'Sagrada Família'), ('SJ', 'São José')], db_index=True, max_length=2)),
                ('data', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, default='')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('conta_envio', models.CharField(blank=True, default='', max_length=200)),
                ('conta_destino', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('EM ABERTO', 'Em Aberto'), ('LANÇADO', 'Lançado'), ('FECHADO', 'Fechado')], db_index=True, default='EM ABERTO', max_length=20)),
                ('observacao', models.TextField(blank=True, default='')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adiantamentos', to='core.motorista')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(choices=[('SF', 'Sagrada Família'), ('SJ', 'São José')], db_index=True, max_length=2)),
                ('data_requisicao', models.DateField(blank=True, null=True)),
                ('data_abastecimento', models.DateField(blank=True, null=True)),
                ('num_requisicao', models.CharField(blank=True, default='', max_length=50)),
                ('qtd_litros', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('vl_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('valor_posto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vl_desconto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('diferenca', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('EM ABERTO', 'Em Aberto'), ('LANÇADO', 'Lançado'), ('FECHADO', 'Fechado')], db_index=True, default='EM ABERTO', max_length=20)),
                ('observacao', models.TextField(blank=True, default='')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimentos', to='core.motorista')),
            ],
            options={
                'ordering': ['-data_requisicao'],
            },
        ),
        migrations.CreateModel(
            name='Romaneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(choices=[('SF', 'Sagrada Família'), ('SJ', 'São José')], db_index=True, max_length=2)),
                ('data', models.DateField(blank=True, null=True)),
                ('nota_fiscal', models.CharField(blank=True, default='', max_length=50)),
                ('ticket', models.CharField(blank=True, default='', max_length=50)),
                ('origem', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('talhao', models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='Talhão')),
                ('destino', models.CharField(blank=True, default='', max_length=200)),
                ('peso_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('EM ABERTO', 'Em Aberto'), ('LANÇADO', 'Lançado'), ('FECHADO', 'Fechado')], db_index=True, default='EM ABERTO', max_length=20)),
                ('observacao', models.TextField(blank=True, default='')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='romaneios', to='core.motorista')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
